### ISSUE TITLE
docker could not start 

### ISSUE THREAD

**Issue by jagadeesh-007** [bobbyiliev/materialize-tutorials#7]
When i give docker-compose up -d  I am getting the following error 

> docker-compose up -d
> Error response from daemon: error while creating mount source path '/var/materialize-tutorials/mz-join-mysql-and-postgresql/mysql_image': mkdir /var/materialize-tutorials: read-only file system

**Comment by bobbyiliev** [comment]
Hi there @jagadeesh-007,

It looks like that you are running your Docker service on a host with a read-only filesystem. Are you running this locally on your laptop? If so can you share a bit more information on your setup?

Alternatively, what you could do is to spin a VM on a Cloud provider like DigitalOcean or AWS and run the demo on there.

**Comment by jagadeesh-007** [comment]
hi @bobbyiliev, 
thanks for the replay, i am using the VM Ubunutu 20.04 OS in my local Lap for testing purpose  and i have given full rights to the folders still I am facing this issue

**Comment by bobbyiliev** [comment]
Hey @jagadeesh-007,

I've been doing some research on that error, it sounds like an issue with the Docker daemon itself:

https://stackoverflow.com/questions/45764477/docker-compose-error-while-creating-mount-source-path

According to the above answer, there are a few solutions:

- Try restarting the Docker service:
```
systemctl restart docker
```

- If this still does not help, try removing the Docker installation in case that it was done with `snap` and then install it with `apt`:

```
snap remove docker
```

Remove the docker directory, and old version (It's okay if these don't exist already):

```
rm -R /var/lib/docker

sudo apt-get remove docker docker-engine docker.io
```

And then install Docker using the official [Docker installation script](https://docs.docker.com/engine/install/ubuntu/):

```
 curl -fsSL https://get.docker.com -o get-docker.sh
 sudo sh get-docker.sh
```

Let me know how it goes.

**Comment by bobbyiliev** [comment]
Hi there,

Just a quick follow up, rather than cloning the repository directly in your `/var` directory, I could suggest cloning it in your user's home directory.

I'm going to close this issue for the moment due to inactivity, but feel free to reopen it or open a new one in case anything else pops up.
